### ISSUE TITLE
Recommendation: Pin SDK version to <2.x

### ISSUE THREAD

**Issue by sirosen** [lliming/globus-id-explorer#1]
Did some friendly poking around and noticed a couple of things.

Three quick notes which might be helpful:

- I'd suggest pinning the SDK to a version range, e.g. `globus_sdk>=1.4.1,<2.0.0`
  I don't know when 2.x will ship (tomorrow, or ten years from today), but by definition it will include breaking changes.
- As of v1.4.0, `decode_id_token` can be called without the auth_client as an input
- As of v1.4.0, `globus_sdk[jwt]` is installed by default. Installing `globus_sdk` in new versions gets you JWT support

You can track our releases and release notes [here](https://github.com/globus/globus-sdk-python/releases) if it's useful to you.

**Comment by lliming** [comment]
Fixed https://github.com/lliming/globus-id-explorer/commit/fca9530a290eb0b27b92a0122df7a6f22a647ea8
